### ISSUE TITLE
Data Rates for ADS1115

### ISSUE THREAD

**Issue by ghost** [hideakitai/ADS1x1x#1]
Thanks for the library.  I found it much more useful and solid than the other one available.
However, I did find one problem that I want to bring to your attention.
The data rate macros only support the 12 bit versions of the family, there doesn't seem to be any support for the data rates of the 16 bit versions like the ADS1115 that I am using.
As a workaround I'm using the 12 bit macros that result in the proper binary value for the 16 bit version, so I'm still using the library, but I did want to bring this to your attention.
Thanks again for the work that went into library....

**Comment by hideakitai** [comment]
Hi @bfcooper , thanks.

> The data rate macros only support the 12 bit versions of the family, there doesn't seem to be any support for the data rates of the 16 bit versions like the ADS1115 that I am using.

This means following API?
```
    adc.datarate(ADS1x1x::ConfigDR::DR_1600_SPS);
```

**Comment by hideakitai** [comment]
@bfcooper Fixed, thanks!
